### ISSUE TITLE
Logical error in web wallet backup flow (incorrect success message and flow continuation)

### ISSUE THREAD

**Issue by cwgoes** [cosmos/fundraiser#1]
The remote wallet backup success notification is displayed and the user is moved forwards to the BTC donation page even when the wallet backup actually failed. The relevant code is in https://github.com/cosmos/fundraiser/blob/develop/src/store/modules/session.js: 

```
client.backupWallet(encryptedSeed, (err) => {
      if (err) {
        console.error(err)
        commit('notifyError', {
          title: 'Wallet Backup Error',
          body: 'An error occurred while backing up your wallet.'
        })
        if (cb) cb(err)
      }
      commit('notifyCustom', {
        title: 'Wallet Backed Up',
        body: 'Your encrypted wallet is now backed up in the Cosmos Fundraiser database.'
      })
      if (cb) cb(null)
    })
```

Note that if an error is thrown, both error and success messages are shown - and the success message is shown after the error message, which may mislead the user into thinking that a wallet backup was successful when in fact it was not - perhaps due to heavy server load or an inconsistent internet connection on the user's part - and that user may go on to delete their local file, leading to unrecoverable funds.

A screenshot of what this looks like in the UI (when the backupWallet call is modified to simulate failure) - the application proceeds onwards to the next step, and the user has no apparent way to go back to check whether or not their backup was successful:

![2017-03-09-205322_2560x1440_scrot](https://cloud.githubusercontent.com/assets/24760279/23779163/c6aec386-050c-11e7-995f-2a14f31952a7.png)

The worst case here is pretty bad: the user thinks their wallet is backed up when it fact it was not, deletes it, and later can't access their funds.

All that's necessary to fix this should be to add a return after the if(cb) cb(err) line in the if(err) block, or to put the success notification and second callback call in an else block.

**Comment by mappum** [comment]
Good find, I forgot to make it return. 😮
